# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: MoonTM-GIT
          template: classic
          base: header, activity, community
          config_timezone: Europe/Berlin
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_habits_days: 30
          plugin_habits_from: 400
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 12
          plugin_lines: yes
          
